// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbydpupppzvnghsvisoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndieWRwdXBwcHp2bmdoc3Zpc29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTEyODMsImV4cCI6MjA2ODkyNzI4M30.mZq_F3JirQKXIQafmCQpKcbDTZ4Bn0SIf1oB-H8Ujg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});